name: Test app
on:
 push: 
    branches: [main, master]
 pull_request: 
    branches: [main, master]
jobs: 
 test: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install deps
      run: npm ci
    
    - name: test code
      run: npm test
        
